# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Practice
  pod 'Alamofire'
#  pod 'Moya'
  pod 'Kingfisher'

end
